export * from "./Home"
export * from "./Login"
export * from "./Register"
export * from "./User/Dashboard"
export * from "./Admin/Dashboard"
export * from "./Admin/UserSection"
export * from "./Admin/SampahSection"
export * from "./Admin/PointSection"